version: "3.8"
services:
  app:
    build: .
    image: bbcredcap3/harness:bs-img # registry/repository:tag
    container_name: bs-cont
    privileged: true
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    volumes:
      - .:/bookstore
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dotfiles/:/home/Shah/
    ports:
      - 8000:8000 # maps the port number 8000 of docker host into port 8000 of container.
    # command: python manage.py runserver 0.0.0.0:8000
